### ISSUE TITLE
Duplicate hover effects for dropdown heading links

### ISSUE THREAD

**Issue by nicwinn** [uthsc/UTHSC#60]
Right now there are no hover effects for the top level items.
![image](https://cloud.githubusercontent.com/assets/9751044/11074492/7f0e1926-87b5-11e5-8896-a2450424da75.png)

Needs to be like so.
![image](https://cloud.githubusercontent.com/assets/9751044/11074801/4b191600-87b7-11e5-975b-d3500553e2ba.png)
I did this by editing the current background

``` css
#uthsc-navigation-alt > ul > li:hover {
    background: -webkit-linear-gradient(top, #0084b6, #0084b6 41px, transparent 41px) !important;
}
```

But this doesn't really work because it remains highlighted when you hover anywhere in the dropdown section
![image](https://cloud.githubusercontent.com/assets/9751044/11074856/a3691756-87b7-11e5-9e44-31af2b8d92ac.png)
